language: ruby
cache: bundler
rvm:
  - 2.3.7
  - 2.4.4
before_script:
  - psql -c 'create database enju_message_dummy_test;' -U postgres
  - psql enju_message_dummy_test -c 'CREATE EXTENSION pgcrypto'
  - bundle exec rake db:migrate
  - bundle exec rake app:sunspot:solr:start
services:
  - redis-server
env:
  - DB=postgresql
notifications:
  slack:
    secure: fRmrMSClIcaF14h4mqbiGT46zYVTKGw7KfyLEHilkz0ny9WEiMYHqQtlbdEfF0r7SE37jghzGTM7Prji3LoZiYlw3DpWh69XLfeBm7gMOv0OxIh/YHYjTHyNGVcEtL6Ab87sApI1BRwf4dHpQxtyENIL49Tce6awzY7l17p0AWg=
sudo: false
addons:
  postgresql: "9.6"
