language: ruby
cache: bundler
rvm:
  - 2.3.8
  - 2.4.6
before_script:
  - mysql -e 'create database enju_test DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;'
  - psql -c 'create database enju_test;' -U postgres
  - bundle exec rake db:migrate
  - bundle exec rake app:sunspot:solr:start
services:
  - redis-server
  - mysql
  - postgresql
env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql
script:
  - bundle exec rspec
notifications:
  slack:
    secure: fRmrMSClIcaF14h4mqbiGT46zYVTKGw7KfyLEHilkz0ny9WEiMYHqQtlbdEfF0r7SE37jghzGTM7Prji3LoZiYlw3DpWh69XLfeBm7gMOv0OxIh/YHYjTHyNGVcEtL6Ab87sApI1BRwf4dHpQxtyENIL49Tce6awzY7l17p0AWg=
sudo: false
addons:
  postgresql: "9.6"
