language: ruby
cache: bundler
rvm:
  - 2.2.5
  - 2.3.1
before_script:
  - psql -c 'create database dummy_test;' -U postgres
  - bundle exec rake db:migrate
services:
  - redis-server
env:
  - DB=postgresql
notifications:
  slack:
    secure: fRmrMSClIcaF14h4mqbiGT46zYVTKGw7KfyLEHilkz0ny9WEiMYHqQtlbdEfF0r7SE37jghzGTM7Prji3LoZiYlw3DpWh69XLfeBm7gMOv0OxIh/YHYjTHyNGVcEtL6Ab87sApI1BRwf4dHpQxtyENIL49Tce6awzY7l17p0AWg=
sudo: false
addons:
  postgresql: "9.4"
  code_climate:
    repo_token: c85c72d27c899b4fa36cf5ea87fca455a56cd1280247befb841ceeee624f788c
